### PR TITLE
major republish and data hall update

### PR DESCRIPTION
**Pull request by anthonie-kramer**
Republish due to accidental deletions...

Also adding some inputs to provide more control in `Data Hall Layout`

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/51)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/51)* status: 1 change requests, 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @anthonie-kramer)

___
*[`LayoutFunctions/DataHall/hypar.json` line 68 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/51#-N_hbQ5v6IPh1FidE8xS:-N_hbQ5v6IPh1FidE8xT:bem9drb) ([raw file](https://github.com/hypar-io/HyparSpace/blob/fd63f024291eff0000f8703d067f1c241daa95ad/LayoutFunctions/DataHall/hypar.json#L68)):*
> ```JSON
>         "$hyparUnitType": "length"
>       },
>       "Flip Direction": {
> ```

Gonna approve this change, but I question whether these should be inputs rather than overrides (perhaps cross-function overrides on the space boundaries, like open office uses). If you have more than one data hall, will you always want to apply these settings the same way to all of them?
___
*[`LayoutFunctions/PantryLayout/dependencies/Floor.g.cs` line 5 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/51#-N_haprJ85KBLSsw6VFR:-N_haprJ85KBLSsw6VFS:bpuby19) ([raw file](https://github.com/hypar-io/HyparSpace/blob/fd63f024291eff0000f8703d067f1c241daa95ad/LayoutFunctions/PantryLayout/dependencies/Floor.g.cs#L5)):*
> ```Smalltalk
> //     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
> // </auto-generated>
> //----------------------
> ```

There should not be a Floor.g.cs (I see it was already committed here, that should not have happened.). Try re-doing `hypar init`. It should figure out that we are already referencing elements and not code-gen `Floor`, which is a built-in type in elements.

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/51)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @anthonie-kramer)

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/51)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @andrewheumann)

___
*[`LayoutFunctions/DataHall/hypar.json` line 68 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/51#-N_hbQ5v6IPh1FidE8xS:-N_oQNGNBVNx2Yj8gY--:b-dxm1ms) ([raw file](https://github.com/hypar-io/HyparSpace/blob/fd63f024291eff0000f8703d067f1c241daa95ad/LayoutFunctions/DataHall/hypar.json#L68)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

Gonna approve this change, but I question whether these should be inputs rather than overrides (perhaps cross-function overrides on the space boundaries, like open office uses). If you have more than one data hall, will you always want to apply these settings the same way to all of them?
</blockquote></details>

Agree that this could be an override... Since the spaces are generated automatically, I do want to apply these conditions to all spaces that are generated, otherwise, I would have to change the properties after each generation.
___
*[`LayoutFunctions/PantryLayout/dependencies/Floor.g.cs` line 5 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/51#-N_haprJ85KBLSsw6VFR:-N_oQhz20JmMv7I0XHZa:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/fd63f024291eff0000f8703d067f1c241daa95ad/LayoutFunctions/PantryLayout/dependencies/Floor.g.cs#L5)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

There should not be a Floor.g.cs (I see it was already committed here, that should not have happened.). Try re-doing `hypar init`. It should figure out that we are already referencing elements and not code-gen `Floor`, which is a built-in type in elements.
</blockquote></details>

Done.
___
*[`LayoutFunctions/PhoneBoothLayout/dependencies/Floor.g.cs` line 20 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/51#-N_iuDdVEB8aYHr67jyW:-N_oQiJQ1p5gmWN-DDs6:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/fd63f024291eff0000f8703d067f1c241daa95ad/LayoutFunctions/PhoneBoothLayout/dependencies/Floor.g.cs#L20)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

See previous note about Floor.g.cs, this needs to be re-`init`-ed
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/51)* status: :shipit: complete! 1 of 1 approvals obtained, all discussions resolved

**Pull request merged**
