### PR TITLE
Migrate Private Office Settings to Cross-function overrides

### PR DESCRIPTION
**Pull request by nadiia-volyk**
This PR depends on https://github.com/hypar-io/Elements/pull/777

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/29)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/29)* status: 1 change requests, 0 of 1 approvals obtained, 4 unresolved discussions (waiting on @nadiia-volyk)

___
*[LayoutFunctions/PrivateOfficeLayout/dependencies/PrivateOfficeLayout.Dependencies.csproj, line 13 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxLSjIDDL6UK8EynlaN:-MxLSjIDDL6UK8EynlaO:b-epyvxm) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/dependencies/PrivateOfficeLayout.Dependencies.csproj#L13)):*
> ```XML
>   <ItemGroup>
>     <Compile Include="../../../ZonePlanningFunctions/SpacePlanningZones/dependencies/SpaceBoundary.cs" />
>     <Compile Include="../../../ZonePlanningFunctions/SpacePlanningZones/dependencies/ProgramRequirement.g.cs" />
> ```

I know these are all required in order to load in `SpaceBoundary.cs`, but my preferred style is actually not to reference dependencies cross-project. I think it should be sufficient to remove this `<ItemGroup>`, and modify the existing `SpaceBoundary.cs` file in this project:

```
public partial class SpaceBoundary : GeometricElement, ISpaceBoundary
{
    public Vector3? ParentCentroid { get; set; }
    public Vector3? IndividualCentroid { get; set; }
}
```

I like to use the corresponding .cs file to add in properties that are not part of the type's schema on an as-needed basis. `SpacePlanningZones`'s `SpaceBoundary.cs` has a bunch of functionality that's not needed here.
___
*[LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, line 16 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxM2cHHDBzJd8UyQql8:-MxM2cHHDBzJd8UyQql9:b-eppfiq) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs#L16)):*
> ```Smalltalk
>     public static class PrivateOfficeLayout
>     {
>         private static readonly List<ElementProxy<SpaceBoundary>> proxies = new List<ElementProxy<SpaceBoundary>>();
> ```

`static` properties can sometimes persist if a lambda stays running — it is good practice to reset these values at the beginning of `Execute` to ensure various executions don't contaminate each other.
___
*[LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, line 108 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxM5Ddz5tCb2MApOhjE:-MxM5Ddz5tCb2MApOhjF:b-q5h61j) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs#L108)):*
> ```Smalltalk
>                                 // {
>                                 //     output.Model.AddElement(new Panel(cinchedPoly, BuiltInMaterials.XAxis, levelVolume.Transform));
>                                 // }
> ```

you can get rid of this commented code I left in here. I was just being sloppy! 
___
*[LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, line 353 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxM2zVU8btdgb6US4c3:-MxM2zVU8btdgb6US4c4:b-sbzbff) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs#L353)):*
> ```Smalltalk
>         }
> 
>         private static ElementProxy<SpaceBoundary> GetElementProxy(SpaceBoundary roofSection, IEnumerable<ElementProxy<SpaceBoundary>> allSpaceBoundaries)
> ```

`roofSection => spaceBoundary`

**Review by andrewheumann — CHANGES_REQUESTED** [review]
Working great! 

> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/29#-:-MxMAdTWDce6fpjURMBk:bx70zc)* status: 1 change requests, 0 of 1 approvals obtained, 4 unresolved discussions (waiting on @nadiia-volyk)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/29)* status: 1 change requests, 0 of 1 approvals obtained, 4 unresolved discussions (waiting on @nadiia-volyk)

**Review by nadiia-volyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/29)* status: 1 change requests, 0 of 1 approvals obtained, 4 unresolved discussions (waiting on @andrewheumann)

___
*[LayoutFunctions/PrivateOfficeLayout/dependencies/PrivateOfficeLayout.Dependencies.csproj, line 13 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxLSjIDDL6UK8EynlaN:-MxZ7ZjI8IizhDgSW43R:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/dependencies/PrivateOfficeLayout.Dependencies.csproj#L13)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I know these are all required in order to load in `SpaceBoundary.cs`, but my preferred style is actually not to reference dependencies cross-project. I think it should be sufficient to remove this `<ItemGroup>`, and modify the existing `SpaceBoundary.cs` file in this project:

```
public partial class SpaceBoundary : GeometricElement, ISpaceBoundary
{
    public Vector3? ParentCentroid { get; set; }
    public Vector3? IndividualCentroid { get; set; }
}
```

I like to use the corresponding .cs file to add in properties that are not part of the type's schema on an as-needed basis. `SpacePlanningZones`'s `SpaceBoundary.cs` has a bunch of functionality that's not needed here.
</blockquote></details>

Done.
___
*[LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, line 16 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxM2cHHDBzJd8UyQql8:-MxZ7_sd921598U2OnlQ:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs#L16)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

`static` properties can sometimes persist if a lambda stays running — it is good practice to reset these values at the beginning of `Execute` to ensure various executions don't contaminate each other.
</blockquote></details>

Done.
___
*[LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, line 108 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxM5Ddz5tCb2MApOhjE:-MxZ7bGG8ldys20EKo_U:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs#L108)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

you can get rid of this commented code I left in here. I was just being sloppy! 
</blockquote></details>

Done.
___
*[LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs, line 353 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/29#-MxM2zVU8btdgb6US4c3:-MxZ7c6O4hDlP-gXOzuq:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/aba83d4142fe8ebee095e55ed825d74157c3c10f/LayoutFunctions/PrivateOfficeLayout/src/PrivateOfficeLayout.cs#L353)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

`roofSection => spaceBoundary`
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/29)* status: :shipit: complete! 1 of 1 approvals obtained, all discussions resolved

**Pull request merged**
