### PR TITLE
create representations for content instances

### PR DESCRIPTION
**Pull request by anthonie-kramer**
* Representations weren't being created for Content Instances due to `Hypar.Elements` and `Hypar.Functions` updates.
* This is a temporary solution until we find the right solution for
https://github.com/hypar-io/Elements/pull/1052

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/70)

### CODE REVIEW

**Comment by anthonie-kramer** [comment]
I'm publishing function-SpaceType with the `LayoutStrategies` change so that it will work with `InteriorPartitions` udpate

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/70)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs` line 58 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/70#-NiZHtJJ8a5sffV6KN3n:-NiZHtJJ8a5sffV6KN3o:bu19zq6) ([raw file](https://github.com/hypar-io/HyparSpace/blob/1e964b2582a5d71b6b4c3c58d445a55a51f25738/LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs#L58)):*
> ```Smalltalk
>             layoutInstantiated.Instance = componentDefinition.Instantiate(ContentConfiguration.AnchorsFromRect(rectangle.TransformedPolygon(xform)));
> 
>             // Ensure that all content items have representations
> ```

Can we leave a TODO to remove this when the corresponding elements PR is merged?

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/70)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs` line 58 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/70#-NiZHtJJ8a5sffV6KN3n:-NidpLOC9XBiUs23YA7c:biit8nr) ([raw file](https://github.com/hypar-io/HyparSpace/blob/1e964b2582a5d71b6b4c3c58d445a55a51f25738/LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs#L58)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

Can we leave a TODO to remove this when the corresponding elements PR is merged?
</blockquote></details>

now that this is merged, can we remove this code and point the function to the correct elements alpha?

**Review by anthonie-kramer — COMMENTED** [review]
This PR is now just an update to the `csproj` since `Elements` can handle the representations now

> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/70#-:-Nien9CUEIe0fYeRHoyA:b-xzgvz0)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @andrewheumann)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs` line 58 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/70#-NiZHtJJ8a5sffV6KN3n:-Nien71WAr4gePqHe0ID:babzd3h) ([raw file](https://github.com/hypar-io/HyparSpace/blob/1e964b2582a5d71b6b4c3c58d445a55a51f25738/LayoutFunctions/LayoutFunctionCommon/LayoutStrategies.cs#L58)):*
<details><summary><i>Previously, andrewheumann (Andrew Heumann) wrote…</i></summary><blockquote>

now that this is merged, can we remove this code and point the function to the correct elements alpha?
</blockquote></details>

Tested and removed

**Review by andrewheumann — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/70)* status: :shipit: complete! 1 of 1 approvals obtained, all discussions resolved

**Pull request merged**
