### PR TITLE
Adjust the Doors function to the changes in the Door class

### PR DESCRIPTION
**Pull request by srudenkoamc**
BACKGROUND
 - Door class has been moved to Elements repo so it can be used during IFC serialization. The Doors function should be modified accordingly.

DESCRIPTION
 - Door class is removed. Modified version of the class is in the Hypar.Elements repo now.
 - Doors function is adjusted to the changes, made in the Door class.
 - Added workarounds for several bugs when several different walls had the same center line.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56)

### CODE REVIEW

**Review by DmytroMuravskyi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56)* status: 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer and @srudenkoamc)

___
*[`LayoutFunctions/Doors/hypar.json` line 66 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-Nch1SCd-PAXJDcKYRkb:-Nch1SCd-PAXJDcKYRkc:b-mvs7ql) ([raw file](https://github.com/hypar-io/HyparSpace/blob/0a015603838dc4885841ba8cad6c4168e234c92a/LayoutFunctions/Doors/hypar.json#L66)):*
> ```JSON
>         "$hyparOrder": 2,
>         "enum": [
>           "SingleSwing",
> ```

These enums are user facing stings, I think whey should have spaces.

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56)* status: 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @anthonie-kramer and @srudenkoamc)

___
*[`LayoutFunctions/Doors/dependencies/Door.cs` line 51 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-Nch8axK75e-X067yCp2:-Nch8axK75e-X067yCp3:b8vkdpk) ([raw file](https://github.com/hypar-io/HyparSpace/blob/0a015603838dc4885841ba8cad6c4168e234c92a/LayoutFunctions/Doors/dependencies/Door.cs#L51)):*
> ```Smalltalk
>             Transform = GetDoorTransform(currentPosition, wallLine, flip);
>             Representation = new Representation(new List<SolidOperation>() { });
>             Opening = new Opening(Polygon.Rectangle(width, height), depthFront, depthBack, GetOpeningTransform(wallLine.Direction()));
> ```

Door transform should be already set up then Opening is created. I think GetOpeningTransform should have no parameters and fully use Door data.

**Comment by srudenkoamc** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56)_ status: 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @anthonie-kramer and @srudenkoamc)
> 
> _[`LayoutFunctions/Doors/hypar.json` line 66 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-Nch1SCd-PAXJDcKYRkb:-Nch1SCd-PAXJDcKYRkc:b-mvs7ql) ([raw file](https://github.com/hypar-io/HyparSpace/blob/0a015603838dc4885841ba8cad6c4168e234c92a/LayoutFunctions/Doors/hypar.json#L66)):_
> 
> > ```json
> >         "$hyparOrder": 2,
> >         "enum": [
> >           "SingleSwing",
> > ```
> 
> These enums are user facing stings, I think whey should have spaces.

Fixed at https://github.com/hypar-io/HyparSpace/pull/56/commits/60834bd2413dbbbf5262610457c27cd69e97433a

**Comment by srudenkoamc** [comment]
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56)_ status: 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @anthonie-kramer and @srudenkoamc)
> 
> _[`LayoutFunctions/Doors/dependencies/Door.cs` line 51 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-Nch8axK75e-X067yCp2:-Nch8axK75e-X067yCp3:b8vkdpk) ([raw file](https://github.com/hypar-io/HyparSpace/blob/0a015603838dc4885841ba8cad6c4168e234c92a/LayoutFunctions/Doors/dependencies/Door.cs#L51)):_
> 
> > ```smalltalk
> >             Transform = GetDoorTransform(currentPosition, wallLine, flip);
> >             Representation = new Representation(new List<SolidOperation>() { });
> >             Opening = new Opening(Polygon.Rectangle(width, height), depthFront, depthBack, GetOpeningTransform(wallLine.Direction()));
> > ```
> 
> Door transform should be already set up then Opening is created. I think GetOpeningTransform should have no parameters and fully use Door data.

Fixed at https://github.com/hypar-io/HyparSpace/pull/56/commits/c2d26d9d652e33b8a883d3ac84879d0ed37e5d03

**Review by anthonie-kramer — APPROVED** [review]
:LGTM:

Do we have a workflow where we are testing the updated Doors function?

> Reviewed 4 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-:-NdgSiwIBFgJgZVgcW29:b79vpob)* status: 1 of 1 approvals obtained, 2 unresolved discussions (waiting on @DmytroMuravskyi)

**Review by anthonie-kramer — CHANGES_REQUESTED** [review]
I think we can pause the work on the Doors function, since we are likely changing the strategy to have the Door created as part of the SpaceBoundary and Wall definitions. Let's just focus on improving the Door class and prepare it to have a relationship with the Wall

> Reviewed 6 of 9 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-:-NibBs-EEJUM5MGfZpco:byfown0)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @DmytroMuravskyi and @srudenkoamc)

___
*[`LayoutFunctions/Doors/src/DoorOpeningEnumsHelper.cs` line 5 at r5](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-NibBgkM820fPPjMd7Zo:-NibBgkM820fPPjMd7Zp:b4sj55f) ([raw file](https://github.com/hypar-io/HyparSpace/blob/50d251fbf98b3a5cdc0c9fc4a8b04f27cd524452/LayoutFunctions/Doors/src/DoorOpeningEnumsHelper.cs#L5)):*
> ```Smalltalk
> namespace Doors
> {
>     internal static class DoorOpeningEnumsHelper
> ```

There aren't many who use the Doors function, so we can change it however we want... In this case, we should just change the override definitions in `hypar.json` to conform to what we need.

**Review by anthonie-kramer — COMMENTED** [review]
@srudenkoamc  Disregard the comment above, I think we will use the `Doors` function as a starting place for the functionality that we want... I will probably try to test this out tomorrow with the updated `Door` class changes...

I think we will still want to generate Doors initially using the `WallCandidate`, and then allow for overrides to change location, and place the `Door` on the closest wall, and cut out an opening... This will probably happen in `Interior Partitions` which means I will make`Doors` a dependency for `Interior Partitions`... I can handle the Wall stuff if you want to get the Door stuff in a good place for me to work with.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/56#-:-NigPsBw0mIbk2aMqJTC:bi8d44u)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @DmytroMuravskyi and @srudenkoamc)

**Pull request merged**
