### PR TITLE
Trim circulation segments to level boundary

### PR DESCRIPTION
**Pull request by nadiia-volyk**
Where a circulation segment extends beyond a floor or level boundary, the geometry is trimmed to the boundary

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/26)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
In general this looks really great — I appreciate the refactoring you've done as well.

I noticed one issue: it is no longer possible to delete segments that have been added. I think this is because we are not correctly setting the `associatedIdentities` on the segments — see notes below. 
[Kapture 2022-02-08 at 08.14.38.mp4](https://files.reviewableusercontent.io/images/reviewable/31935763/PSAOEpcD3Ms5y_eapWeSQ4cn/Kapture%202022-02-08%20at%2008.14.38.mp4)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/26#-:-MvOTHCq4NWYRLISZ5ie:b6rx7ct)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @nadiia-volyk)

___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 166 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/26#-MvOTohk19I-6h3YZF3g:-MvOTohl8ua0ba1Ek0n9:b-o5cejq) ([raw file](https://github.com/hypar-io/hyparspace/blob/63163285cc0cd828b11880b004c5566b212c499c/ZonePlanningFunctions/Circulation/src/Circulation.cs#L166)):*
> ```Smalltalk
>                                 corridorProfiles.Add(circulationSegment.Profile);
>                                 circulationSegments.Add(circulationSegment);
>                                 Identity.AddOverrideIdentity(circulationSegment.Profile, addedCorridor);
> ```

I think this should be `Identity.AddOverrideIdentity(circulationSegment, addedCorridor);` — we want to add the `associatedIdentities` information to the segment element itself, not its profile.

**Review by nadiia-volyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/26)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @andrewheumann)

___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 166 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/26#-MvOTohk19I-6h3YZF3g:-MvUsdEF-zLcsGG_lTtf:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/63163285cc0cd828b11880b004c5566b212c499c/ZonePlanningFunctions/Circulation/src/Circulation.cs#L166)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think this should be `Identity.AddOverrideIdentity(circulationSegment, addedCorridor);` — we want to add the `associatedIdentities` information to the segment element itself, not its profile. 
</blockquote></details>

Done.

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/26)* status: :shipit: complete! 1 of 1 approvals obtained, all discussions resolved

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/26)* status: :shipit: complete! 1 of 1 approvals obtained, all discussions resolved

**Pull request merged**
