### PR TITLE
Column avoidance merge

### PR DESCRIPTION
**Pull request by lelandjobson**
Culls desks based on locations from "Structure" or "Columns" function.

Usage:
- Add to a hypar workflow where Space Planning Zones and Structure / Columns functions exist.
- Desks will be placed in designated Space Planning Zones where columns are not present.

Notes:
- Some code comments removed from OpenOfficeLayout.cs
- Test model jsons added from Column Problem 1  and Column Problem 2
- Adds `SearchablePointCollection<T>` class which can be used to get closest elements / elements within boundary fast
   - Usage:
       - SearchablePointCollection<Chair> means you can add tuples of (Vector3, Chair) to the collection. Provided a single point or range, you can retreive all of the closest Chairs to a point or Chairs within a range.
       - `<T>` and the location don't have to be correlated, such as a chair and its location on the plan. For example, you can have the Vector3 represent non-positional and qualitative values

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)* status: 1 change requests, 0 of 1 approvals obtained, 11 unresolved discussions (waiting on @lelandjobson)

___
*[LayoutFunctions/.vs/slnx.sqlite, line 0 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKvZMe2YRwYtNIrHB9:-MqKvZMfEp7wGSbrBv-6:b-folg2b) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/.vs/slnx.sqlite#L0)):*
not sure what this file is (and maybe it was already in there?) — maybe we need `.vs` in the gitignore?
___
*[LayoutFunctions/OpenOfficeLayout/__hypar.json, line 2 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKvIkP7mgt5wtbIYNF:-MqKvIkP7mgt5wtbIYNG:bkuz1mp) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/__hypar.json#L2)):*
> ```JSON
> {
>   "$schema": "https://hypar.io/Schemas/Function.json",
> ```

Let's go ahead and restore the original ID and delete `_hypar.json` prior to merge
___
*[LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, line 87 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKxcpL9befoNn_tcfo:-MqKxcpL9befoNn_tcfp:bf66405) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs#L87)):*
> ```Smalltalk
>             List<(Vector3,Profile)> modelColumnLocations = new List<(Vector3,Profile)>();
>             foreach(var source in _columnSources){
>                 if(inputModels.ContainsKey(source)){
> ```

just a personal preference but I tend to do 
```if(inputModels.TryGetValue(source, out var sourceData)) {...}``` to check / access in one go
___
*[LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, line 283 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKx3bk-EJ1_CYSgK3B:-MqKx3bk-EJ1_CYSgK3C:bnngzm7) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs#L283)):*
> ```Smalltalk
>                                 {
>                                     desksSkippedTotal++;
>                                     continue;                                   
> ```

There's some weird white space stuff going on in a few of the files... do me a favor and give everything a once over with vs code's default `format document` command?
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 12 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-isK7-BgWXXyxKn8:-MqL-isK7-BgWXXyxKn9:b-s1w8lb) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L12)):*
> ```Smalltalk
>     /// or near a location
>     /// </summary>
>     public class SearchablePointCollection<T> {
> ```

Let's leave a TODO: in here about moving this out of this function and into `Elements`.
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 20 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL4RcC8O1Ut0MQrARO:-MqL4RcDBxkR0GReEkDG:b6letz6) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L20)):*
> ```Smalltalk
>          = new List<SortedDictionary<double, List<Vector3>>>();
> 
>          List<List<double>> _keys => __keys ?? (__keys = _coords.Select(c => c.Keys.ToList()).ToList());
> ```

this can use compound assignment
```
_keys => __keys ??= _coords.Select(c => c.Keys.ToList()).ToList()
```
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 21 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKy12-7cDj-jFRHJfk:-MqKy12-7cDj-jFRHJfl:b-j9uxjf) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L21)):*
> ```Smalltalk
> 
>          List<List<double>> _keys => __keys ?? (__keys = _coords.Select(c => c.Keys.ToList()).ToList());
>          List<List<double>> __keys;
> ```

I think these are implicitly private but let's give 'em `private` so it's clear
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 77 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKzj43CMZNXYOX9vEB:-MqKzj43CMZNXYOX9vEC:b-1bt0uf) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L77)):*
> ```Smalltalk
>         }
> 
>         public bool IsWithinTolerance(double a, double b, double tolerance){
> ```

I think this is the same as the elements extension method `a.ApproximatelyEquals(b, tolerance)`  (and you don't seem to be using it anyway, so let's get rid of it)
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 86 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL22azDXTm42YY_ckw:-MqL22b-A-CBfIa3WY2p:busapoy) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L86)):*
> ```Smalltalk
>             for(int i = 0; i<bounds.Count; i++){
>                 List<Vector3> found = new List<Vector3>();
>                 int dMin = Math.Max(0,(~_keys[i].BinarySearch(bounds[i].Item1 - tolerance) - 1));
> ```

Any place you're using a `(double, double)` tuple type, make it a named tuple `(double min, double max)` or `(double x, double y)` etc — I have a personal vendetta against seeing `.Item1` `.Item2` in code 
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 196 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-SBY-fgCf3_ITQZS:-MqL-SBY-fgCf3_ITQZT:b-gebtzp) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L196)):*
> ```Smalltalk
> 
>         double GetDimensionalValue(int dim, Vector3 point){
>             switch(dim){
> ```

If you wanna get fancy schmancy, this can be:
```
 return dim switch
            {
                0 => point.X,
                1 => point.Y,
                2 => point.Z,
                _ => throw new Exception($"Can't handle dimension {dim}"),
            };
```
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 210 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-HOPC2opZWZ803m_:-MqL-HOPC2opZWZ803ma:b-aen1wq) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L210)):*
> ```Smalltalk
>         
>         (double,double) GetDimensionalRange(int dim, BBox3 bounds){
>             switch(dim){
> ```

same as above, this can be 
```
return dim switch
            {
                0 => (bounds.Min.X, bounds.Max.X),
                1 => (bounds.Min.Y, bounds.Max.Y),
                2 => (bounds.Min.Z, bounds.Max.Z),
                _ => throw new Exception($"Can't handle dimension {dim}"),
            };
```

**Review by andrewheumann — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)* status: 1 change requests, 0 of 1 approvals obtained, 10 unresolved discussions (waiting on @lelandjobson)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)* status: 1 change requests, 0 of 1 approvals obtained, 10 unresolved discussions (waiting on @lelandjobson)

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)* status: 1 change requests, 0 of 1 approvals obtained, 10 unresolved discussions (waiting on @lelandjobson)

**Review by lelandjobson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)* status: 1 change requests, 0 of 1 approvals obtained, 10 unresolved discussions (waiting on @andrewheumann)

___
*[LayoutFunctions/.vs/slnx.sqlite, line  at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKvZMe2YRwYtNIrHB9:-MqL6O568yEMUAIRrj-X:bd8d4sv) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/.vs/slnx.sqlite#L)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

not sure what this file is (and maybe it was already in there?) — maybe we need `.vs` in the gitignore?
</blockquote></details>

Idk either "shrug"
___
*[LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, line 87 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKxcpL9befoNn_tcfo:-MqL6vyB1-wijvqAyY7K:be0z4jg) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs#L87)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

just a personal preference but I tend to do 
```if(inputModels.TryGetValue(source, out var sourceData)) {...}``` to check / access in one go
</blockquote></details>

that's fair - for people that code in multiple languages it's pretty common to make this mistake bc not all languages have this implemented. I saw containskey was used on line 70 and line 124, prior to my work
___
*[LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, line 283 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKx3bk-EJ1_CYSgK3B:-MqL75SN3CSYHunpH8zW:b7rj0ti) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs#L283)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

There's some weird white space stuff going on in a few of the files... do me a favor and give everything a once over with vs code's default `format document` command?
</blockquote></details>

Done.  I do add newlines more frequently. Generally I try to keep lines 100 chars or less in width so that you can actually work with multiple tabs. I also add newlines in method chains a la D3 so its more legible
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 12 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-isK7-BgWXXyxKn8:-MqL7O9fBwPfJCy5Fkzz:bhnsz5i) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L12)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Let's leave a TODO: in here about moving this out of this function and into `Elements`.
</blockquote></details>

Yep sure
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 20 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL4RcC8O1Ut0MQrARO:-MqL8cvm-Q4IMSREWqpL:bvnm4wk) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L20)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

this can use compound assignment
```
_keys => __keys ??= _coords.Select(c => c.Keys.ToList()).ToList()
```
</blockquote></details>

picky motherfucker
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 21 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKy12-7cDj-jFRHJfk:-MqL8h2s13AuYrFWn9OV:b-n61yz3) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L21)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think these are implicitly private but let's give 'em `private` so it's clear
</blockquote></details>

totally a good idea 
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 77 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKzj43CMZNXYOX9vEB:-MqL8ues81GR8UkzLzd-:b-7rl0kd) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L77)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think this is the same as the elements extension method `a.ApproximatelyEquals(b, tolerance)`  (and you don't seem to be using it anyway, so let's get rid of it)
</blockquote></details>

done
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 86 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL22azDXTm42YY_ckw:-MqL8w-wCh3uFsOBrwtl:b-7rl0kd) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L86)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

Any place you're using a `(double, double)` tuple type, make it a named tuple `(double min, double max)` or `(double x, double y)` etc — I have a personal vendetta against seeing `.Item1` `.Item2` in code 
</blockquote></details>

done
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 196 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-SBY-fgCf3_ITQZS:-MqL9cq83hol1jMSBrE8:b-6hsmak) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L196)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

If you wanna get fancy schmancy, this can be:
```
 return dim switch
            {
                0 => point.X,
                1 => point.Y,
                2 => point.Z,
                _ => throw new Exception($"Can't handle dimension {dim}"),
            };
```
</blockquote></details>

that's stylish af. i usually do the boring old way bc it helps transitioning between multiple languages. hope thats reasonable
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 210 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-HOPC2opZWZ803m_:-MqL9rNgAhPP-FGPGZIp:b-c41p0p) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L210)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

same as above, this can be 
```
return dim switch
            {
                0 => (bounds.Min.X, bounds.Max.X),
                1 => (bounds.Min.Y, bounds.Max.Y),
                2 => (bounds.Min.Z, bounds.Max.Z),
                _ => throw new Exception($"Can't handle dimension {dim}"),
            };
```
</blockquote></details>

same as above stylish af

**Review by andrewheumann — APPROVED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/19)* status: 1 of 1 approvals obtained, 2 unresolved discussions (waiting on @lelandjobson)

___
*[LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs, line 283 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqKx3bk-EJ1_CYSgK3B:-MqLAau4AmcI9Z1NHtza:b-5vr0im) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/OpenOfficeLayout.cs#L283)):*
<details><summary><i>Previously, lelandjobson (Leland Jobson ) wrote…</i></summary><blockquote>

Done.  I do add newlines more frequently. Generally I try to keep lines 100 chars or less in width so that you can actually work with multiple tabs. I also add newlines in method chains a la D3 so its more legible
</blockquote></details>

yeah very much in favor of that too (even if this code doesn't reflect it :upside_down_face: )
___
*[LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs, line 196 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/19#-MqL-SBY-fgCf3_ITQZS:-MqLAr1A7jejcefM5omC:b-x779wg) ([raw file](https://github.com/hypar-io/hyparspace/blob/587a72eecd27a4a813eac78d33fbe75b54a79cb6/LayoutFunctions/OpenOfficeLayout/src/SearchablePointCollection.cs#L196)):*
<details><summary><i>Previously, lelandjobson (Leland Jobson ) wrote…</i></summary><blockquote>

that's stylish af. i usually do the boring old way bc it helps transitioning between multiple languages. hope thats reasonable
</blockquote></details>

I buy that. But fix the indentation!

**Pull request merged**
