### PR TITLE
Create WallCandidate objects in Interior Partitions function

### PR DESCRIPTION
**Pull request by nadiia-volyk**
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/38)

### CODE REVIEW

**Review by serenayl — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/38)* status: 1 change requests, 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @nadiia-volyk and @wynged)

___
*[`LayoutFunctions/InteriorPartitions/src/InteriorPartitions.cs` line 53 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/38#-NWEvl5r1sA1eoewhh6y:-NWEvl5r1sA1eoewhh6z:b-pjstca) ([raw file](https://github.com/hypar-io/HyparSpace/blob/338ab56b7f24faca2be734e7926a504fe3856112/LayoutFunctions/InteriorPartitions/src/InteriorPartitions.cs#L53)):*
> ```Smalltalk
>                 var candidates = WallGeneration.DeduplicateWallLines(levelGroup.ToList());
>                 var height = levelGroup.OrderBy(l => l.Height).FirstOrDefault()?.Height ?? 3;
>                 var wallCandidates = candidates.Select(c => new WallCandidate(c.line.TransformedLine(levelGroup.Key), c.type, new List<SpaceBoundary>()));
> ```

For this PR, is it intended that we don't populate this list? We can put that part in later if you want to make it a TODO!
___
*[`LayoutFunctions/LayoutFunctionCommon/WallGeneration.cs` line 216 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/38#-NWEvNjdCEwE4XcR8lED:-NWEvNjdCEwE4XcR8lEE:b-jcdff5) ([raw file](https://github.com/hypar-io/HyparSpace/blob/338ab56b7f24faca2be734e7926a504fe3856112/LayoutFunctions/LayoutFunctionCommon/WallGeneration.cs#L216)):*
> ```Smalltalk
>         }
> 
>         public static void GenerateWalls(Model model, IEnumerable<(Line Line, string Type, Guid ElementId)> wallCandidateLines, double height, Transform levelTransform, bool debugMode = false)
> ```

Nit: I'm not sure if this is standard practice in C# but this shadowed variable name feels somewhat confusing? Does it need to become capitalized in the tuple?

**Review by nadiia-volyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/38)* status: 1 change requests, 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @serenayl and @wynged)

___
*[`LayoutFunctions/InteriorPartitions/src/InteriorPartitions.cs` line 53 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/38#-NWEvl5r1sA1eoewhh6y:-NWbK0ZZ7GSqXmrbCIOe:b-3gmy8u) ([raw file](https://github.com/hypar-io/HyparSpace/blob/338ab56b7f24faca2be734e7926a504fe3856112/LayoutFunctions/InteriorPartitions/src/InteriorPartitions.cs#L53)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

For this PR, is it intended that we don't populate this list? We can put that part in later if you want to make it a TODO!
</blockquote></details>

yes, it is intended
___
*[`LayoutFunctions/LayoutFunctionCommon/WallGeneration.cs` line 216 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/38#-NWEvNjdCEwE4XcR8lED:-NWbMZAFBs2_42PE9mRf:b-4muva7) ([raw file](https://github.com/hypar-io/HyparSpace/blob/338ab56b7f24faca2be734e7926a504fe3856112/LayoutFunctions/LayoutFunctionCommon/WallGeneration.cs#L216)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Nit: I'm not sure if this is standard practice in C# but this shadowed variable name feels somewhat confusing? Does it need to become capitalized in the tuple?
</blockquote></details>

Reverted capitalizing

**Review by wynged — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/38)* status: 1 change requests, 1 of 1 approvals obtained, 2 unresolved discussions (waiting on @serenayl)

**Review by nadiia-volyk — COMMENTED** [review]
> Dismissed @serenayl from a discussion.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/38)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained, all discussions resolved (waiting on @serenayl)

**Review by serenayl — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/38)* status: :shipit: complete! 2 of 1 approvals obtained, all discussions resolved

**Pull request merged**
