### PR TITLE
Layout Function Cleanup

### PR DESCRIPTION
**Pull request by nadiia-volyk**
Move duplicated code to LayoutGeneration class with a few virtual methods that are overridden in specific layout functions

Differences in layouts after cleanup are [here](https://www.notion.so/hyparaec/Layout-differences-075a152f778247848d05518773c69050)

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37)

### CODE REVIEW

**Review by serenayl — CHANGES_REQUESTED** [review]
> Reviewed 16 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @andrewheumann, @nadiia-volyk, and @wynged)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 50 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXROJWa5n5B9APM7kjM:-NXROJWa5n5B9APM7kjN:b-geq3ot) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L50)):*
> ```Smalltalk
>             foreach (var lvl in levels)
>             {
>                 var corridors = lvl.Elements.Where(e => e is Floor).OfType<Floor>();
> ```

I'm not as familiar with this code, so I'm curious why this was changed from `lvl.Elements.OfType<CirculationSegment>()`?



_Code quote:_
```Smalltalk
lvl.Elements.Where(e => e is Floor).OfType<Floor>()
```
___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 243 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXRMeZg2bzIJotEbpV5:-NXRMeZg2bzIJotEbpV6:b-e06doi) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L243)):*
> ```Smalltalk
>         }
> 
>         protected virtual IEnumerable<TLevelElements> GetLevels(Dictionary<string, Model> inputModels, Model spacePlanningZones)
> ```

Can we add a comment that `GetLevels` also assigns the relevant circulation segments to those levels?
___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 276 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXRNCuv6RRRnHw6zM52:-NXRNCuv6RRRnHw6zM53:bwdw540) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L276)):*
> ```Smalltalk
>             }
>             return levelVolumes;
>         }
> ```

This method already seems to exist in `LayoutStrategies`, do we need to replicate it here?



_Code quote:_
```Smalltalk
        private static List<TLevelVolume> GetLevelVolumes(Dictionary<string, Model> inputModels)
        {
            var levelVolumes = new List<TLevelVolume>();
            if (inputModels.TryGetValue("Levels", out var levelsModel))
            {
                levelVolumes.AddRange(levelsModel.AllElementsAssignableFromType<TLevelVolume>());
            }
            if (inputModels.TryGetValue("Conceptual Mass", out var massModel))
            {
                levelVolumes.AddRange(massModel.AllElementsAssignableFromType<TLevelVolume>());
            }
            return levelVolumes;
        }
```

**Review by nadiia-volyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @andrewheumann, @serenayl, and @wynged)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 50 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXROJWa5n5B9APM7kjM:-NaBv1YqAuz7zoKRZ5zv:b-f8ku1u) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L50)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

I'm not as familiar with this code, so I'm curious why this was changed from `lvl.Elements.OfType<CirculationSegment>()`?
</blockquote></details>

This code was from LayoutStrategies. I don't see reason for it. Changed it to TCirculationSegment
___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 243 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXRMeZg2bzIJotEbpV5:-NaBvU8R5uiwSVi3uVUJ:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L243)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Can we add a comment that `GetLevels` also assigns the relevant circulation segments to those levels?
</blockquote></details>

Done.
___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 276 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXRNCuv6RRRnHw6zM52:-NaBvw_r4Kvtws4EihGZ:b-l0xkpp) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L276)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

This method already seems to exist in `LayoutStrategies`, do we need to replicate it here?
</blockquote></details>

No. Removed it

**Comment by nadiia-volyk** [comment]
My test workflow - https://hypar.io/workflows/1d11bd4a-5c93-45ff-92b8-a9ac11d5664b

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 19 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @serenayl and @wynged)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 50 at r1](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NXROJWa5n5B9APM7kjM:-NaI3tWe839uTUPQnYHM:bvoldw5) ([raw file](https://github.com/hypar-io/HyparSpace/blob/a0e8bfafd180986f448da4602a6281a24dbcc707/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L50)):*
<details><summary><i>Previously, nadiia-volyk wrote…</i></summary><blockquote>

This code was from LayoutStrategies. I don't see reason for it. Changed it to TCirculationSegment
</blockquote></details>

This is a good change, anything treating circulation as a floor is old / out of date :)

**Review by wynged — COMMENTED** [review]
@andrewheumann  @serenayl  documentation of these changes is here.  Look for New #2, looks pretty good to me! https://www.notion.so/hyparaec/Document-layout-differences-075a152f778247848d05518773c69050?pvs=4

> Reviewed 9 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-:-Nagy0Z2Dplr9nu_FMeL:b-lr4jcq)* status: 1 change requests, 0 of 1 approvals obtained, 3 unresolved discussions (waiting on @serenayl)

**Review by serenayl — CHANGES_REQUESTED** [review]
The layout mostly looks good but it looks like we've lost our `Collaboration Seat` count. Before and after:



> Reviewed 14 of 17 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-:-Nari0Rq1eXkoooKYlhp:b-3y4sy8)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @nadiia-volyk)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 94 at r3](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NarioEh5ZmPgNTxK74M:-NarioEh5ZmPgNTxK74N:bca1im6) ([raw file](https://github.com/hypar-io/HyparSpace/blob/6d78212a6c58c8b511bacbec4031a0817252c5f2/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L94)):*
> ```Smalltalk
> 
>                     totalSeats += seatsCount;
>                     outputModel.AddElement(new SpaceMetric(room.Id, seatsCount, 0, 0, 0));
> ```

See here for where I suspect we are losing seats.



_Code quote:_
```Smalltalk
outputModel.AddElement(new SpaceMetric(room.Id, seatsCount, 0, 0, 0))
```

**Review by nadiia-volyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/HyparSpace/37)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @serenayl)

___
*[`LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs` line 94 at r3](https://reviewable.io/reviews/hypar-io/HyparSpace/37#-NarioEh5ZmPgNTxK74M:-NazylDE4qoC5HVscQWR:b-896fix) ([raw file](https://github.com/hypar-io/HyparSpace/blob/6d78212a6c58c8b511bacbec4031a0817252c5f2/LayoutFunctions/LayoutFunctionCommon/LayoutGeneration.cs#L94)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

See here for where I suspect we are losing seats.
</blockquote></details>

Done.

**Pull request merged**
