### PR TITLE
Adjust the geometry of the CirculationSegment

### PR DESCRIPTION
**Pull request by nadiia-volyk**
- Trim corridor polygon along polyline to prevent angled overhangs
- Extend corridor polygon along polyline to prevent small gaps
- Trim circulation segments to level boundary after corridors clean up

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/27)

### CODE REVIEW

**Review by andrewheumann — CHANGES_REQUESTED** [review]
This looks and feels great — really nice work. Here are a few cases where I noticed some unintended odd behavior:

Strange end condition:
https://hypar.io/workflows/f87576a3-128a-4a20-b8d9-7468842d2b85


Odd case with a bending corridor
https://hypar.io/workflows/f42f12c9-2d0a-40c5-8371-e1e29d449efb


> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/27#-:-MwXyHzz0_Xk7ClGXg4x:bjromwf)* status: 1 change requests, 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @nadiia-volyk)

___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 811 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/27#-MwY1SoC1VyxQY568FbW:-MwY1SoC1VyxQY568FbX:bozdx8u) ([raw file](https://github.com/hypar-io/hyparspace/blob/7f274ff3ad4193a4fc9538b8abb6f9b3f4f0139a/ZonePlanningFunctions/Circulation/src/Circulation.cs#L811)):*
> ```Smalltalk
>         {
>             var resultProfile = new Profile(profile.Perimeter, profile.Voids, profile.Id, profile.Name);
>             var maxDistance = Math.Min(2 * corridorPolyline.Width, corridorPolyline.Polyline.Length() / 3);
> ```

I think we should use a smaller max distance, now having played with it. Perhaps just 1*width? 
___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 940 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/27#-MwXkZIq74S3uiC57QGu:-MwXkZIq74S3uiC57QGv:b-5vabut) ([raw file](https://github.com/hypar-io/hyparspace/blob/7f274ff3ad4193a4fc9538b8abb6f9b3f4f0139a/ZonePlanningFunctions/Circulation/src/Circulation.cs#L940)):*
> ```Smalltalk
>         }
> 
>         private static bool SegmentsOverlap(Line a, Line b)
> ```

This method shows up a lot now — we should probably move it into Elements! Feel free to do that if you have some time (not a requirement for this PR though).

**Review by nadiia-volyk — COMMENTED** [review]
The first case can be fixed by using smaller max distance, but a similar problem might still occur.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/27#-:-Mx0AkkdDTDjRJB05C8T:bdtnk2o)* status: 1 change requests, 0 of 1 approvals obtained, 2 unresolved discussions (waiting on @andrewheumann)

___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 811 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/27#-MwY1SoC1VyxQY568FbW:-Mx07L0C7tFgbamSinCB:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/7f274ff3ad4193a4fc9538b8abb6f9b3f4f0139a/ZonePlanningFunctions/Circulation/src/Circulation.cs#L811)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

I think we should use a smaller max distance, now having played with it. Perhaps just 1*width? 
</blockquote></details>

Done.
___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 940 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/27#-MwXkZIq74S3uiC57QGu:-Mx08-md-Dimue4IPTac:b-qwxzxx) ([raw file](https://github.com/hypar-io/hyparspace/blob/7f274ff3ad4193a4fc9538b8abb6f9b3f4f0139a/ZonePlanningFunctions/Circulation/src/Circulation.cs#L940)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

This method shows up a lot now — we should probably move it into Elements! Feel free to do that if you have some time (not a requirement for this PR though). 
</blockquote></details>

As I see, new method `TryGetOverlap` was recently added to Elements. But there is one problem, I described it in the PR https://github.com/hypar-io/Elements/pull/774. I think this method can be used instead after it is fixed.

**Review by andrewheumann — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/27)* status: 1 change requests, 0 of 1 approvals obtained, 1 unresolved discussion (waiting on @nadiia-volyk)

___
*[ZonePlanningFunctions/Circulation/src/Circulation.cs, line 940 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/27#-MwXkZIq74S3uiC57QGu:-Mx1RDJI0s11t9kCUItW:b4c9lyr) ([raw file](https://github.com/hypar-io/hyparspace/blob/7f274ff3ad4193a4fc9538b8abb6f9b3f4f0139a/ZonePlanningFunctions/Circulation/src/Circulation.cs#L940)):*
<details><summary><i>Previously, nadiia-volyk wrote…</i></summary><blockquote>

As I see, new method `TryGetOverlap` was recently added to Elements. But there is one problem, I described it in the PR https://github.com/hypar-io/Elements/pull/774. I think this method can be used instead after it is fixed.
</blockquote></details>

:thumbsup:

**Review by andrewheumann — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/27#-:-Mx1fMoi7NVI6Vys_7HK:bnfp4nl)* status: 1 of 1 approvals obtained, 1 unresolved discussion (waiting on @nadiia-volyk)

**Pull request merged**
