### PR TITLE
add manual circulation options

### PR DESCRIPTION
**Pull request by andrewheumann**
- This looks like a huge PR, but it's mostly just lots of refactoring (it's still a bit of a mess)
- enable an option to provide manually drawn circulation instead of automatically drawn

TESTING
- verified that generates reasonable results with manually drawn circulation
- verified that results are unchanged with automatic circulation

COMMENTS
- Won't publish function until https://github.com/hypar-io/Explore/pull/1237 is merged, to ensure new inputs get correct default values.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/3)

### CODE REVIEW

**Review by wynged — APPROVED** [review]
I like the refactor, much methods, very good.

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/3#-:-MXbYeZ63dGlYbVbNKHk:bgydik)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @andrewheumann)

___
*[ZonePlanningFunctions/SpacePlanningZones/hypar.json, line 46 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/3#-MXbWOuS1SKF5ttfxqxP:-MXbWOuS1SKF5ttfxqxQ:b-xq1b6r) ([raw file](https://github.com/hypar-io/hyparspace/blob/f3451d3686d8b6efb665f6964d28beae58160b9d/ZonePlanningFunctions/SpacePlanningZones/hypar.json#L46)):*
> ```JSON
>             },
>             "Circulation Mode": {
>                 "description": "How should circulation be calculated? \nAutomatic: a typical circulation network will be generated for you. \nManual: you draw the circulation paths yourself.",
> ```

Capital 'A' typical and 'Y'ou draw maybe?  If you think that looks worse feel free to ignore.
___
*[ZonePlanningFunctions/SpacePlanningZones/README.md, line 5 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/3#-MXbXL4RAXKtlhtGVTUw:-MXbXL4RAXKtlhtGVTUx:b5t2ig1) ([raw file](https://github.com/hypar-io/hyparspace/blob/f3451d3686d8b6efb665f6964d28beae58160b9d/ZonePlanningFunctions/SpacePlanningZones/README.md#L5)):*
> ```Markdown
> # Space Planning Zones
> 
> TEST - Generate a circulation path and high-level zones for a schematic space plan.
> ```

This "TEST -" somehow snuck through

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @andrewheumann)

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[ZonePlanningFunctions/SpacePlanningZones/hypar.json, line 46 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/3#-MXbWOuS1SKF5ttfxqxP:-MXb_Br1831SpPX14iCy:b-56sn2) ([raw file](https://github.com/hypar-io/hyparspace/blob/f3451d3686d8b6efb665f6964d28beae58160b9d/ZonePlanningFunctions/SpacePlanningZones/hypar.json#L46)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

Capital 'A' typical and 'Y'ou draw maybe?  If you think that looks worse feel free to ignore.
</blockquote></details>

gonna ignore — typically you wouldn't capitalize after a colon. 
___
*[ZonePlanningFunctions/SpacePlanningZones/README.md, line 5 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/3#-MXbXL4RAXKtlhtGVTUw:-MXb_LaUDrmWGGNFVVYT:bnwjkw0) ([raw file](https://github.com/hypar-io/hyparspace/blob/f3451d3686d8b6efb665f6964d28beae58160b9d/ZonePlanningFunctions/SpacePlanningZones/README.md#L5)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

This "TEST -" somehow snuck through
</blockquote></details>

ahh good catch. I fixed it in hypar.json but didn't `init` after.

**Review by andrewheumann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/hyparspace/3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @wynged)

___
*[ZonePlanningFunctions/SpacePlanningZones/README.md, line 5 at r1](https://reviewable.io/reviews/hypar-io/hyparspace/3#-MXbXL4RAXKtlhtGVTUw:-MXb_x522f_OxiZTDqnz:b-896fix) ([raw file](https://github.com/hypar-io/hyparspace/blob/f3451d3686d8b6efb665f6964d28beae58160b9d/ZonePlanningFunctions/SpacePlanningZones/README.md#L5)):*
<details><summary><i>Previously, andrewheumann wrote…</i></summary><blockquote>

ahh good catch. I fixed it in hypar.json but didn't `init` after.
</blockquote></details>

Done.

**Pull request merged**
